a5q5: academic.o board.o Chance_and_Community_chest.o main.o monopoly.o player.o square_ownable.o square_unownable.o square.o
	g++ -Werror=vla -std=c++11 -ferror-limit=0 -g  academic.o board.o Chance_and_Community_chest.o main.o monopoly.o player.o square_ownable.o square_unownable.o square.o -o a5q5
	
square.o: square.cpp
	g++ -Werror=vla -std=c++11 -ferror-limit=0 -g -c square.cpp

square_ownable.o: square_ownable.cpp
	g++ -Werror=vla -std=c++11 -ferror-limit=0 -g -c square_ownable.cpp

square_unownable.o: square_unownable.cpp
	g++ -Werror=vla -std=c++11 -ferror-limit=0 -g -c square_unownable.cpp

academic.o: academic.cpp
	g++ -Werror=vla -std=c++11 -ferror-limit=0 -g -c academic.cpp

board.o: board.cpp
	g++ -Werror=vla -std=c++11 -ferror-limit=0 -g -c board.cpp

Chance_and_Community_chest.o: Chance_and_Community_chest.cpp
	g++ -Werror=vla -std=c++11 -ferror-limit=0 -g -c Chance_and_Community_chest.cpp

main.o: main.cpp
	g++ -Werror=vla -std=c++11 -ferror-limit=0 -g -c main.cpp

monopoly.o: monopoly.cpp
	g++ -Werror=vla -std=c++11 -ferror-limit=0 -g -c monopoly.cpp

main.o: main.cpp
	g++ -Werror=vla -std=c++11 -ferror-limit=0 -g -c main.cpp

player.o: player.cpp
	g++ -Werror=vla -std=c++11 -ferror-limit=0 -g -c player.cpp


clean:
	rm *.o a5q5